#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

USE_PROCD=1
BIN=mobile-mngr
MOBILE_DIR=/var/mobile

start_service() {
    echo "start mobile-mngr"

    [ ! -d ${MOBILE_DIR} ] && mkdir ${MOBILE_DIR}
    [ ! -f ${MOBILE_DIR}/simlock_support ] && touch ${MOBILE_DIR}/simlock_support
    [ ! -f ${MOBILE_DIR}/bandlock_support ] && touch ${MOBILE_DIR}/bandlock_support
    [ ! -f ${MOBILE_DIR}/voltecs_support ] && touch ${MOBILE_DIR}/voltecs_support
    [ ! -f ${MOBILE_DIR}/celllock_support ] && touch ${MOBILE_DIR}/celllock_support

    procd_open_instance
    procd_set_param respawn
    procd_set_param command "$BIN"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    echo "stop mobile-mngr"
}

restart() {
    stop
    start
}