#!/bin/sh

if [ $# -ne 1 ]; then
        exit 255
fi

# $1 is uci lan interface name, default name is 'lan', and this is a linux bridge interface
uciif="$1"

# add or remove wifi interface from bridge
for ifname in `ls /sys/class/net | grep ^ra`; do
        # echo ifname=$ifname
                                                                  
        ifstatus=`cat /sys/class/net/$ifname/carrier 2> /dev/null`
        if [ "$ifstatus" = "1" ]; then                                                              
                # echo $ifname linkup                                                               
                ubus call network.interface.$uciif add_device    {\"name\":\"$ifname\"} 2> /dev/null
                if [ $? -eq 0 ]; then                                         
                        echo $ifname linkup, try to add it to bridge br-$uciif
                fi                                                                               
        else                                                                                     
                # echo $ifname linkdown                                                          
                ubus call network.interface.lan remove_device {\"name\":\"$ifname\"} 2> /dev/null
                if [ $? -eq 0 ]; then                                                
                        echo $ifname linkdown, try to delete it from bridge br-$uciif
                fi
        fi
done
 